#!/bin/bash
echo "Debugging task creation issue..."
echo ""
echo "1. Checking if binary is updated:"
ls -lh unicli
echo ""
echo "2. Current tasks in DB:"
sqlite3 ~/.unicli/unicli.db "SELECT id, title, status FROM tasks ORDER BY created_at DESC LIMIT 3;"
echo ""
echo "3. Database file info:"
ls -lh ~/.unicli/unicli.db
echo ""
echo "Instructions to test in the app:"
echo "  1. Run: ./unicli"
echo "  2. Press: :s (open sidebar)"
echo "  3. Navigate to Tasks and press Enter"
echo "  4. Press: n (new task)"
echo "  5. Fill the form:"
echo "     - Title: Test Creation $(date +%s)"
echo "     - Press Tab to move between fields"
echo "     - Navigate to Submit button (press Tab multiple times)"
echo "     - Press Enter on Submit button"
echo "  6. Exit with :q"
echo ""
echo "Then run this to check:"
echo "  sqlite3 ~/.unicli/unicli.db \"SELECT title, created_at FROM tasks ORDER BY created_at DESC LIMIT 1;\""
