#!/bin/bash
echo "🧪 Quick Test - Task Creation"
echo ""
echo "1. Current task count:"
sqlite3 ~/.unicli/unicli.db "SELECT COUNT(*) FROM tasks;"
echo ""
echo "2. Run the app now:"
echo "   ./unicli"
echo ""
echo "3. Create a task:"
echo "   :s → Tasks → n → Title: 'Test Fix 123' → Tab → Tab → Tab → Tab → Enter"
echo ""
echo "4. After creating, run this script again to verify:"
echo "   ./QUICK_TEST.sh"
echo ""
read -p "Press Enter after you've created the task..."
echo ""
echo "Checking..."
NEW_COUNT=$(sqlite3 ~/.unicli/unicli.db "SELECT COUNT(*) FROM tasks;")
echo "New task count: $NEW_COUNT"
echo ""
echo "Latest tasks:"
sqlite3 ~/.unicli/unicli.db "SELECT title, status, created_at FROM tasks ORDER BY created_at DESC LIMIT 3;"
echo ""
echo "📋 Logs:"
echo "--- TASKFORM ---"
tail -5 /tmp/unicli_taskform_debug.log 2>/dev/null || echo "No logs yet"
echo ""
echo "--- TASKSCREEN ---"
tail -5 /tmp/unicli_taskscreen_debug.log 2>/dev/null || echo "No logs yet"
